import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Homepage from "./Homepage";
// import Homepage from "./Homepage";

// PAGES

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
 
  return (
    <section className="oo">
      <Head>
        <title>JUSMIN EMPIRE</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          href="https://res.cloudinary.com/dnfa3ujys/image/upload/v1685984511/WhatsApp_Image_2023-06-05_at_3.43.15_PM_xrkz2v.jpg"
        />
      </Head>
      <main className="app-main-con">
        {/* HOOME PAE */}

        <Homepage />
      </main>
    </section>
  );
}
